### ISSUE TITLE
Adding -Me option for Method selection

### ISSUE THREAD

**Issue by s-tobe** [migcm/nagios-check_curl#2]
Hi I have added the following option in my local version of the script

-Me POST (in order to support htpps method POST for example)

Could you add that the a new version of the script?

cheers
s-tobe
...
switch ($argv[$i]) {
            **case '-Me':
                if ($Pocet > $i + 1) {
                    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, $argv[++$i]);
                    if ($Debug)
                        echo "\nDEBUG: -Me " . $argv[$i];
                } else {
                    echo "UNKNOWN - ERROR in parsing argument -Me: missing value\n";
                    exit(3);
                }
                break;**
            case '-U':
....

**Comment by migcm** [comment]
It's already updated. Thank you very much for the contribution.
