### ISSUE TITLE
Adding options for proxy

### ISSUE THREAD

**Issue by tmorik** [migcm/nagios-check_curl#4]
Hello,

I'd like to suggest the following options for proxy settings. Could you take a look and added them to a new version of check_curl if you think they are ok?

```
case '-Px':
	if ($Pocet > $i + 1) {
		curl_setopt($ch, CURLOPT_PROXY, $argv[++$i]);
		if ($Debug)
			echo "\nDEBUG: -Px " . $argv[$i];
	} else {
		echo "UNKNOWN - ERROR in parsing argument -Px: missing value\n";
		exit(3);
	}
	break;

case '-PxPort':
	if ($Pocet > $i + 1) {
		curl_setopt($ch, CURLOPT_PROXYPORT, $argv[++$i]);
		if ($Debug)
			echo "\nDEBUG: -PxPort " . $argv[$i];
	} else {
		echo "UNKNOWN - ERROR in parsing argument -PxPort: missing value\n";
		exit(3);
	}
	break;

case '-PxAuth':
	if ($Pocet > $i + 1) {
		curl_setopt($ch, CURLOPT_PROXYUSERPWD, $argv[++$i]);
		if ($Debug)
			echo "\nDEBUG: -PxAuth " . $argv[$i];
	} else {
		echo "UNKNOWN - ERROR in parsing argument -PxPort: missing value\n";
		exit(3);
	}
	break;    
```

**Comment by migcm** [comment]
Hello!

It is a very good idea, if you want, do a pull request with the modification.

Thanks for helping!

**Comment by tmorik** [comment]
Thanks! I will do a pull request :)  Did you want me to create a new branch and do a pull? Or just using master? Sorry, I'm new to GitHub and looks like I cannot create a new branch to your repo due to a permission...

**Comment by tmorik** [comment]
FYI - I followed this way : https://gist.github.com/Chaser324/ce0505fbed06b947d962 (made my fork and send a pull request).

**Comment by migcm** [comment]
Hello! 

It's very good. I've tested and [merged](https://github.com/migcm/nagios-check_curl/commit/311e395940650b8162e6a789ee7d20e6f1960aaa) it.

Thank you! =).
