### ISSUE TITLE
contradictory size options

### ISSUE THREAD

**Issue by facenn** [migcm/nagios-check_curl#6]
Hello,
maybe it´s a misunderstanding of the readme from myself but it seems that the options Sbc,Soc,Sbw and Sow are not working as expected.

Example 1: 
./check_curl -U https://XXXXXXXX/sitemap-1.xml -Sbc 5000000  -F 
CRITICAL -  Page size 21332497B below limit 5000000B | |time=6.961 size=21332497

In that case I would have expect an okay state because the size of the side is greater than my threshold. 

Example 2:
/nagios-check_curl$ ./check_curl -U https://XXXXXXX/sitemap-1.xml -Soc 5000000  -F 
OK -  Page size 21332497 between the limits | |time=5.297 size=21332497

The reverse of example 1. I would have expect an critical state due the size of the page is greater than my threshold.

If you switch the greater and lesser sign in the ifelse statements it should work fine.

Can you please take a look.

Thank you.

**Comment by migcm** [comment]
Hello,

Sorry, I didn't see this issue. If you want, make a pull request. I test it and merge to master :).

Thanks a lot!
